config/routes.rb
Miniblog::Application.routes.draw do
  resources :products

  resources :friendships, :only => [:create, :destroy]

  resources :favorites, :only =>[:create, :destroy]

resources :tweets, :only => [:show, :create, :destroy] do
  	post :retweet, :on => :member
end
	
  devise_for :users, :controllers => {
  	:registrations => "users/registrations",
  	:sessions => "users/sessions"
  }
  
  resources :users, :only => [:index, :show] do
  	get "following", :on => :member
  	get "followers", :on => :member
  	get "favorites", :on => :member
  end

  get "home" => "pages#home"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  get "terms" => "pages#terms"
  get "help" => "pages#help"
 
  root :to => "pages#home"
  root :to => "products#index"
    
 

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
has_many :favorites, :dependent => :destroy
belongs_to :user

belongs_to :original_tweet, :class_name => "Tweet"
has_many :retweets, :class_name => "Tweet", :foreign_key => "original_tweet_id"

 def retweet_by(retweeter)
 	if self.user == retweeter
 		"Sorry, you can't retweet your own tweets"
 	elsif self.retweets.where(:user_id => retweeter.id).present?
 		"You already retweeted!"
 	else retweeter.tweets.create(
 		:content => "RT #{self.user.username}: #{self.content}",
 		:original_tweet => self
 		)
 		"Succesfully retweeted"
 	end
end

#presence...if contents is brank, it become error
validates :user_id, :content, :presence => true
validates :content, :length => {:maximum => 140}
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
before_filter :authenticate_user!, :only=>[:show, :create, :destroy]
	def show
	@tweet = Tweet.find(params[:id])
	end
	
   def create
    @tweet = current_user.tweets.build(params[:tweet])
    if @tweet.save
    	flash[:notice] = 'Tweet was succrssfully created.'
    else
    	flash[:alert] = 'Tweet was not created.'
    end
    redirect_to root_url
    #respond_to do |format|
      #if @tweet.save
        #format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        #format.json { render json: @tweet, status: :created, location: @tweet }
      #else
        #format.html { render action: "new" }
        #format.json { render json: @tweet.errors, status: :unprocessable_entity }
      #end
    #end
  end

  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
	redirect_to root_url
    #respond_to do |format|
      #format.html { redirect_to tweets_url }
      #format.json { head :no_content }
    #end
  end
  
  def retweet
  	original_tweet = Tweet.find(params[:id])
  	flash[:notice] = original_tweet.retweet_by(current_user)
  	redirect_to root_path
  end
  
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div>
	<%= link_to tweet.user.username, tweet.user %>
	<%= tweet.content %>
	<small>(<%= link_to time_ago_in_words(tweet.created_at)+" ago", tweet %> )</small>
	<% if user_signed_in? %>
		<% if current_user == tweet.user %>
			<%#= link_to "Delete", tweet, :method => "delete", remote => true %>
			<%= link_to "Delete", tweet, :method => "delete" %>
		<% else %>
			<%= link_to "Retweet", retweet_tweet_path(tweet), :method => "post" %>
		<% end %>
	<% end %>
		<%= link_to_favorite(tweet) %>		
</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>User</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.user_id %></td>
    <td><%= tweet.content %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>
<div>
	<%= render @tweet %>
</div>