config/routes.rb
Miniblog::Application.routes.draw do
  resources :products

  resources :friendships, :only => [:create, :destroy]

  resources :favorites, :only =>[:create, :destroy]

resources :tweets, :only => [:show, :create, :destroy] do
  	post :retweet, :on => :member
end
	
  devise_for :users, :controllers => {
  	:registrations => "users/registrations",
  	:sessions => "users/sessions"
  }
  
  resources :users, :only => [:index, :show] do
  	get "following", :on => :member
  	get "followers", :on => :member
  	get "favorites", :on => :member
  end

  get "home" => "pages#home"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  get "terms" => "pages#terms"
  get "help" => "pages#help"
 
  root :to => "pages#home"
  root :to => "products#index"
    
 

end

app/views/shared/_footer.html.erb
<hr />
<div id ="footer">
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Privacy", privacy_path %></li>
		<li><%= link_to "Terms", terms_path %></li>		
		<li><%= link_to "Help", help_path %></li>
	</ul>
</div>

app/views/shared/_header.html.erb
<div id ="header">
	<ul>
			<li><%= link_to "User", users_path %></li>
		<% if user_signed_in? %>
			<li><%= link_to "Profile", current_user %></li>
			<li>Logged in as <%= current_user.email %></li>
			<li><%= link_to('Logout', destroy_user_session_path, :method => :delete)%></li>
			<li><%= link_to('Edit registration', edit_user_registration_path) %></li>
		<% else %>
			<li><%= link_to('Login', new_user_session_path) %></li>
			<li><%= link_to('Register', new_user_registration_path) %></li>
		<% end %>
	</ul>
</div>
<hr />